# This file lists translatable strings used in the Android app which don't appear anywhere else
# in the Electrum repository. Some of them only differ in capitalization or punctuation:
# see https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98

# If you change anything here, you need to rebuild the Android strings files by running the
# Gradle task `generateStrings`.

def _(s):
    return s

_("Block explorer")
_("Copyright © 2017-2019 Electrum LLC and the Electrum developers.")
_("Cannot specify private keys and addresses in the same wallet.")
_("Change password")
_("Close wallet")
_("Confirm password")
_("Current password")
_("Console")
_("Delete_wallet")
_("Derivation invalid")
_("Disconnect")
_("ID")
_("Enter password")
_("For support, please visit us on <a href='https://github.com/Electrum/Electrum/issues'>"
  "GitHub</a> or on <a href='https://t.me/electrumwallet'>Telegram</a>.")
_("Import addresses or private keys")
_("Invalid address")
_("Made with <a href='https://chaquo.com/chaquopy'>Chaquopy</a>, the Python SDK for Android.")
_("New password")
_("New wallet")
_("No wallet")
_("No wallet is open.")
_("Not a valid address or private key: '%s'")
_("Passphrase")
_("Press the menu button above to open or create one.")
_("Request")
_("Restore from seed")
_("Show seed")
_("Size")
_("Transaction not found")
_("Use a master key")
_("Wallet seed")
_("You don't have any contacts.")

_("electrum_is_generating_your_addresses__please_wait_")
_("are_you_sure_you_wish_to_delete")
_("something_went") 
_("no_wallet_is_open_") 
_("if_your") 
_("connected_to") 
_("chain_split") 
_("not_a_valid") 
_("please_enter_your_seed_phrase") 
_("please_enter_your_seed_derivation") 
_("please_save") 
_("this_wallet_is") 
_("are_you_sure_you_wish_to_proceed") 
_("this_wallet_is") 
_("electrum_is_generating_your_addresses__please_wait_") 
_("sat_byte") 
_("plurals") 
_("bytes") 
_("sat_byte") 
_("text_copied") 
_("no_wallet_is_open_")
_("electrum_is_generating_your_addresses__please_wait_")
_("new_password")
